<?php

namespace epixilog\moviesBundle\Repository;
use Doctrine\ORM\EntityRepository;

use epixilog\moviesBundle\Utils\Slug as Slugs;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

	public function getWithCount(){
		$qb = $this->createQueryBuilder('c')
					->select('c.id, c.label, count(cf.id) as ccf')
					->orderBy('ccf', 'DESC')
					->leftJoin('c.category_films', 'cf')
					->groupBy('c.label')
					->getQuery();
					
		$results =  $qb->getResult();

		for($i=0; $i<count($results); $i++){
			$results[$i]['slug'] = Slugs::slugify($results[$i]['label']);
		}

		return $results;
	}

	

}
