epixilogpages:
    resource: "@epixilogpagesBundle/Resources/config/routing.yml"
    prefix:   /

epixilogmovies:
    resource: "@epixilogmoviesBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
