services:
      twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }
#    epixilogpages.example:
#        class: epixilog\pagesBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
