epixilog\moviesBundle\Entity\Category:
  type: entity
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    label:
      type: string
      length: 200
      unique: true
    description:
      type: string
      length: 2500
  oneToMany:
    category_films:
      targetEntity: CategoryFilm
      mappedBy: category