epixilog\moviesBundle\Entity\CategoryFilm:
  type: entity
  table: category_film
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    pertinence:
      type: float
      nullable: true
  manyToOne:
    category:
      targetEntity: Category
      inversedBy: category_films
      joinColumn:
        name: category_id
        referencedColumnName: id
    film:
      targetEntity: Film
      inversedBy: category_films
      joinColumn:
        name: film_id
        referencedColumnName: id