epixilog\moviesBundle\Entity\Film:
  type: entity
  table: film
  repositoryClass: epixilog\moviesBundle\Repository\FilmRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
    description:
      type: text
    slug:
      type: string
      length: 355
    created_at:
      type: datetime
    updated_at:
      type: datetime
  oneToMany:
    category_films:
      targetEntity: CategoryFilm
      mappedBy: film
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue, setSlugValue ]
    preUpdate: [ setUpdatedAtValue, setSlugValue ]